[build]
  command = "npm run build"
  publish = "out"

[[redirects]]
  from = "/app/projects/*"
  to = "/app/projects.html"
  status = 200

[[redirects]]
  from = "/chat/*"
  to = "/chat.html"
  status = 200

[[redirects]]
  from = "/app/*"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
